version: '3.7'

services:
  account-pg:
    restart: always
    image: postgres:alpine
    container_name: account-pg
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=account
